# EasyAdminBundle Configuration
easy_admin:
    list:
        actions:
            - { name: 'show' }
            - { name: 'new', icon: 'plus', label: 'app.admin.new' }
        max_results: 20
    design:
        menu:
#            - { label: 'app.admin.solution', entity: 'Solution', default: true}
#            - { label: 'app.admin.user', entity: 'User'}
#            - { label: 'app.admin.maturity_card', entity: 'MaturityCard', params: { action: 'new' } }
        brand_color: '#1ABC9C'
        form_theme: ['horizontal', 'VichUploaderBundle:Form:fields.html.twig']
    site_name: 'RolePlay'
    entities:
#        Domain:
#            class: AppBundle\Entity\Taxonomy\Domain
#            image_base_path: '%vich.path.domain_image%'
#            label: 'app.admin.domain'
#            list:
#                title: 'app.admin.list.domain'
#                fields:
#                    - { property: 'id', label: 'app.admin.taxonomy.id' }
#                    - { property: 'name', label: 'app.admin.taxonomy.name' }
#                    - { property: 'image', label: 'app.admin.domain.image', type: 'image' }
#            new:
#                fields:
#                    - { property: 'name', label: 'app.admin.taxonomy.name' }
#                    - { property: 'imageFile', type: 'vich_image', label: 'app.admin.domain.image' }
#            edit:
#                fields:
#                    - { property: 'name', label: 'app.admin.taxonomy.name' }
#                    - { property: 'imageFile', type: 'vich_image', label: 'app.admin.domain.image', type_options: { required: false, allow_delete: false }}
#            show:
#                title: 'app.admin.show.domain'
#                fields:
#                    - { property: 'id', label: 'app.admin.taxonomy.id' }
#                    - { property: 'name', label: 'app.admin.taxonomy.name' }
#                    - { property: 'image', label: 'app.admin.domain.image', type: 'image' }
#            new:
#                title: 'app.admin.new.domain'
#            edit:
#                title: 'app.admin.edit.domain'
#        Solution:
#            controller: AppBundle\Controller\EasyAdmin\SolutionController
#            class: AppBundle\Entity\Solution
#            label: 'app.admin.solution'
#            list:
#                title: 'app.admin.list.solution'
#                fields:
#                    - { property: 'id', label: 'app.admin.solution.id' }
#                    - { property: 'name', label: 'app.admin.solution' }
#            form:
#                fields:
#                    - { property: 'name', label: 'app.admin.solution'}
#                    - { property: 'imageFiles', type: 'collection', label: 'app.admin.solution.images', type_options: { entry_type: 'AppBundle\Form\ImageFileType', by_reference: false }}
#                    - { property: 'thematic', label: 'app.admin.solution.thematic', type_options: { required: true } }
#                    - { property: 'regionalDirectorates', type: 'AppBundle\Form\RegionalDirectorateType', label: 'app.admin.solution.regional_directorate', type_options: { required: true } }
#                    - { property: 'sensitiveInfo', type: 'choice', label: 'app.admin.solution.sensitive_info', type_options: { required: true, choices: { 'Oui': true, 'Non': false } } }
#                    - { property: 'headline', type: 'ckeditor', label: 'app.admin.solution.headline' }
#                    - { property: 'jobImpacts', label: 'app.admin.solution.impacted_professions', type_options: { required: true } }
#                    - { property: 'keywords', type: 'easyadmin_autocomplete', label: 'app.admin.solution.keywords' }
#            show:
#                title: 'app.admin.show.solution'
#                fields:
#                    - { property: 'id', label: 'app.admin.solution.id' }
#                    - { property: 'name', label: 'app.admin.solution' }
#                    - { property: 'imageFiles', label: 'app.admin.solution.images', template: 'image_files.html.twig', base_path: '%vich.path.domain_image%' }
#            new:
#                title: 'app.admin.new.solution'
#            edit:
#                title: 'app.admin.edit.solution'