# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~
#        cartel_provider:
#            entity:
#                class: AppBundle:HumanResources\Employee
#                property: username

        api_key_user_provider:
            id: api_key_user_provider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        secured_area:
            pattern: ^/api
            stateless: false
            simple_preauth:
                authenticator: apikey_authenticator
            provider: api_key_user_provider
        main:
            anonymous: ~
#        main:
#            pattern: ^/
#            http_basic: ~
#            provider: cartel_provider
#            anonymous: ~
#            logout:
#                path:   /logout
#                target: /login
#            form_login:
#                login_path: login
#                check_path: login
#                default_target_path: /
#
    access_control:
#        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY  }
        - { path: ^/api, roles: ['ROLE_USER', 'ROLE_API'] }
#        - { path: ^/, roles: ROLE_USER }