# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
#        FOS\UserBundle\Model\UserInterface: sha512
        Symfony\Component\Security\Core\User\User: plaintext
#        AppBundle\Entity\Character:
#            algorithm: bcrypt
#            cost: 12
    role_hierarchy:
        ROLE_USER: ROLE_USER
        ROLE_ADMIN: ROLE_ADMIN
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        roleplay_provider:
#            entity:
#                class: AppBundle:Character
#                property: name
            memory:
                users:
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
                    user: { password: test, roles: [ 'ROLE_USER' ] }
        api_key_user_provider:
            id: api_key_user_provider
#        fos_userbundle:
#            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        secured_area:
            pattern: ^/api
            stateless: false
            simple_preauth:
                authenticator: apikey_authenticator
            provider: api_key_user_provider
        main:
            pattern: ^/
            http_basic: ~
            provider: roleplay_provider
            anonymous: ~
#            anonymous: true
            logout:
                path:   /logout
                target: /login
            form_login:
#                provider: fos_userbundle
                login_path: login
                check_path: login
                default_target_path: /

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: ['ROLE_USER', 'ROLE_API', 'ROLE_ADMIN'] }
        - { path: ^/admin, roles: 'ROLE_ADMIN' }
        - { path: ^/, roles: ['ROLE_USER', 'ROLE_ADMIN'] }