# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\:
        resource: '%kernel.project_dir%/src/AppBundle/*'
        exclude: '%kernel.project_dir%/src/AppBundle/{Entity,Repository,Tests,Resources,Fixtures}'

    AppBundle\Manager\:
        public: true
        resource: '%kernel.project_dir%/src/AppBundle/Manager'

    AppBundle\Service\:
        public: true
        resource: '%kernel.project_dir%/src/AppBundle/Service'

#    AppBundle\Service\SolutionExportService:
#        public: true
#        arguments: ['%export_solution%']

#    AppBundle\Twig\MyTwigExtension:
#        tags: [twig.extension]

#    app_bundle.security.http.authentication.login_success_handler:
#        class:  AppBundle\Security\Http\Authentication\LoginAuthenticationSuccessHandler
#        arguments:
#            - '@security.http_utils'
#            - '@router'
