services:
    cms_default_manager:
        class: AppBundle\Service\DefaultManager
        arguments: ["@doctrine.orm.entity_manager", "%picture_directory%"]
    cms_character_manager:
        class: AppBundle\Service\CharacterManager
        arguments: ["@doctrine.orm.entity_manager", "%picture_directory%", "@security.token_storage"]
    cms_module_manager:
        class: AppBundle\Service\ModuleManager
        arguments: ["@doctrine.orm.entity_manager", "%picture_directory%"]
    cms_universe_manager:
        class: AppBundle\Service\UniverseManager
        arguments: ["@doctrine.orm.entity_manager", "%picture_directory%"]
    cms_event_manager:
        class: AppBundle\Service\EventManager
        arguments: ["@doctrine.orm.entity_manager", "%picture_directory%"]
    cms_option_manager:
        class: AppBundle\Service\OptionManager
        arguments: ["@doctrine.orm.entity_manager", "%picture_directory%"]
    api_key_user_provider:
        class: AppBundle\Security\ApiKeyUserProvider
    apikey_authenticator:
        class:  AppBundle\Security\ApiKeyAuthenticator
        arguments: ["@api_key_user_provider"]