services:
    cms_default_manager:
        class: AppBundle\Service\DefaultManager
        arguments: ["@doctrine.orm.entity_manager"]
    api_key_user_provider:
        class: AppBundle\Security\ApiKeyUserProvider
    apikey_authenticator:
        class:  AppBundle\Security\ApiKeyAuthenticator
        arguments: ["@api_key_user_provider"]